-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
-- -- local opts = { noremap = true, silent = true }
-- vim.keymap.set("n", "<leader>cen", vim.lsp.diagnostic.goto_next())
-- vim.keymap.set("n", "<leader>cep", vim.lsp.diagnostic.goto_prev())
